services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    restart: unless-stopped
    ports:
      - "8096:8096"
      - "8920:8920" 
    volumes:
      - ./config/emby/config:/config
      - ./data/media:/data/media
    environment:
      - EMBY_PublishedServerUrl=http://${IP}:8096  # Optional: Set your server URL
      - TZ=Europe/Dublin

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"  # Radarr web interface
    volumes:
      - ./config/radarr/config:/config  # Radarr configuration files
      - ./data:/data
      - ./data:/downloads
      - ./data/media/movies:/movies
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"  # Sonarr web interface
    volumes:
      - ./config/sonarr/config:/config  # Sonarr configuration files
      - ./data:/data
      - ./data/downloads:/downloads
      - ./data/media/tv:/tv
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  jackett:
      image: lscr.io/linuxserver/jackett:latest
      restart: unless-stopped
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=Europe/Dublin
        - AUTO_UPDATE=true
      volumes:
        - ./config/jackett:/config
        - ./data/indexing-jackett:/downloads
      ports:
        - 9117:9117

  deluge:
    image: lscr.io/linuxserver/deluge
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Dublin
    volumes:
      - ./config/deluge:/config
      - ./data/torrents:/data/torrents
      - ./data/indexing:/data/indexing
      - ./data/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
